environment:
  env_source: stanford_robosuite
  env_name: Lift

robosuite_env:
  env_name: Lift
  robots: Panda
  has_renderer: False
  has_offscreen_renderer: False
  use_camera_obs: False
  use_object_obs: True                  
  horizon: 200
  reward_shaping: True

robosuite_keys: ["robot0_robot-state", "object-state"]

training_params:
  num_epochs: 100
  num_episodes: 1
  episode_horizon: 1000
  warmup: 100
  render: True

ddpg_agent:
  state_dim: 42
  action_dim: 8
  action_high: 1.
  action_low: -1.
  hidden_size: 300 
  lr_actor: 0.001 
  lr_critic: 0.001 
  tau: 0.005 
  gamma: 0.99 
  eps: 1.0
  decay_eps: 0.001 
  batch_size: 64 
  max_mem_size: 500000