wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
gamma:
  desc: null
  value: 0.99
horizon:
  desc: null
  value: 10
num_episodes:
  desc: null
  value: 2
