environment:
  env_name: InvertedDoublePendulum-v2

training_params:
  num_epochs: 100
  num_episodes: 10
  episode_horizon: 1000
  warmup: 100
  render: True

ddpg_agent:
  state_dim: 11
  action_dim: 1 
  action_high: 1.
  action_low: -1.
  hidden_size: 300 
  lr_actor: 0.001 
  lr_critic: 0.001 
  tau: 0.005 
  gamma: 0.99 
  eps: 1.0
  decay_eps: 0.0001 
  batch_size: 64 
  max_mem_size: 500000